AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Streaming app API

Globals:
  Function:
    Timeout: 15
    CodeUri: src
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Environment:
      Variables:
        BUCKET_NAME: !Ref ContentsBucket
        TABLE_NAME: !Ref ContentsTable

Resources:
  ContentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub "${AWS::StackName}-contents-table"
      AttributeDefinitions:
        - AttributeName: fileKey
          AttributeType: S
      KeySchema:
        - AttributeName: fileKey
          KeyType: HASH

  ContentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-contents-bucket"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
            ExposedHeaders: 
              - ETag
            AllowedOrigins:
              - http://localhost:5173

  ContentsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub ${AWS::StackName}-contents-api
      CorsConfiguration:
          AllowOrigins:
            - http://localhost:5173
          AllowHeaders:
            - "*"
          AllowMethods:
            - POST
            - GET
    
  UploadContentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/http/getSignedUrl.handler
      FunctionName: !Sub ${AWS::StackName}-upload-content
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ContentsBucket
        - S3WritePolicy:
            BucketName: !Ref ContentsBucket
        - DynamoDBWritePolicy:
            TableName: !Ref ContentsTable
      Events:
        GetSignedUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContentsHttpApi
            Path: /upload
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShaking: true
        Bundle: true
        Sourcemap: false
        EntryPoints:
          - functions/http/getSignedUrl.ts 

  InitiateMPUFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/http/mpu/initiateMPU.handler
      FunctionName: !Sub ${AWS::StackName}-initiate-mpu
      Events:
        InitiateMPU:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContentsHttpApi
            Path: /initiate-mpu
            Method: post
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ContentsBucket
        - S3WritePolicy:
            BucketName: !Ref ContentsBucket
        - DynamoDBWritePolicy:
            TableName: !Ref ContentsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShaking: true
        Bundle: true
        Sourcemap: false
        EntryPoints:
          - functions/http/mpu/initiateMPU.ts 

  CompleteMPUFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/http/mpu/completeMPU.handler
      FunctionName: !Sub ${AWS::StackName}-complete-mpu
      Events:
        CompleteMPU:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContentsHttpApi
            Path: /complete-mpu
            Method: post
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ContentsBucket
        - S3WritePolicy:
            BucketName: !Ref ContentsBucket
        - DynamoDBWritePolicy:
            TableName: !Ref ContentsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShaking: true
        Bundle: true
        Sourcemap: false
        EntryPoints:
          - functions/http/mpu/completeMPU.ts 

  AbortMPUFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/http/mpu/abortMPU.handler
      FunctionName: !Sub ${AWS::StackName}-abort-mpu
      Events:
        AbortMPU:
          Type: HttpApi
          Properties:
            ApiId: !Ref ContentsHttpApi
            Path: /abort-mpu
            Method: post
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ContentsBucket
        - DynamoDBWritePolicy:
            TableName: !Ref ContentsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShaking: true
        Bundle: true
        Sourcemap: false
        EntryPoints:
          - functions/http/mpu/abortMPU.ts 

  FindAndDeleteMPUFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/http/mpu/findAndDeleteMPUs.handler
      FunctionName: !Sub ${AWS::StackName}-find-and-delete-mpus
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:ListBucketMultipartUploads
            Resource: !GetAtt ContentsBucket.Arn
        - Statement:
            Effect: Allow
            Action:
              - s3:AbortMultipartUpload
            Resource: !Sub "${ContentsBucket.Arn}/*"
        - DynamoDBWritePolicy:
            TableName: !Ref ContentsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShaking: true
        Bundle: true
        Sourcemap: false
        EntryPoints:
          - functions/http/mpu/findAndDeleteMPUs.ts

  UploadedContentTrigger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/s3/uploadedContentTrigger.handler
      FunctionName: !Sub ${AWS::StackName}-uploaded-content-trigger
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ContentsBucket
        - DynamoDBWritePolicy:
            TableName: !Ref ContentsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        TreeShaking: true
        Bundle: true
        Sourcemap: false
        EntryPoints:
          - functions/s3/uploadedContentTrigger.ts

Outputs:
  UploadContentFunction:
    Description: UploadContentFunction Lambda Function ARN
    Value: !GetAtt UploadContentFunction.Arn
  UploadContentFunctionIamRole:
    Description: Implicit IAM Role created for UploadContentFunction
    Value: !GetAtt UploadContentFunctionRole.Arn
